# Generated by Django 3.1.7 on 2021-03-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210330_2127'),
        ('users', '0009_user_is_two_factor_enabled'),
    ]

    operations = [
    ]
